name: Build

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04-8core
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "npm"

      - name: Run Tests
        run: |
          npm ci --workspaces
          npm run build --workspace=packages/espresso-block-explorer-components
          npm ci --workspaces
          cp packages/espresso-block-explorer-components/dist/*.js packages/block-explorer/public/.
          mkdir -p packages/block-explorer/public/assets
          cp packages/espresso-block-explorer-components/dist/assets/*.js packages/block-explorer/public/assets/.
          npm run lint --workspaces
          npm run test --workspaces
          npm run coverage --workspaces

      - name: Components Coverage Main Branch
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          name: "Espresso Block Explorer Components"
          working-directory: "./packages/espresso-block-explorer-components/"
          file-coverage-mode: all

      - name: Components Coverage Pull Request
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          name: "Espresso Block Explorer Components"
          working-directory: "./packages/espresso-block-explorer-components/"
          file-coverage-mode: changes

      - name: Generate Storybook Static Files for Espresso Block Explorer Components
        run: |
          npm --workspace=packages/espresso-block-explorer-components run build-storybook

      - name: Deploy Espresso Block Explorer Components Storybook
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/espresso-block-explorer-components/storybook-static
