name: Build

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Tests
        run: |
          npm ci --workspaces
          npm run lint --workspaces
          npm run test --workspaces
          npm run coverage --workspaces

      - name: Components Coverage Main Branch
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          name: "Espresso Block Explorer Components"
          working-directory: "./packages/espresso-block-explorer-components/"
          file-coverage-mode: all

      - name: Components Coverage Pull Request
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          name: "Espresso Block Explorer Components"
          working-directory: "./packages/espresso-block-explorer-components/"
          file-coverage-mode: changes

      - name: Generate Storybook Static Files for Espresso Block Explorer Components
        run: |
          npm --workspace=packages/espresso-block-explorer-components run build-storybook

      - name: Deploy Espresso Block Explorer Components Storybook
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/espresso-block-explorer-components/storybook-static
